services:
  postgres:
    image: postgres:16
    container_name: binomo2_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: binomo2
    ports:
      - "5433:5432"   # другой порт хоста для postgres
    volumes:
      - postgres2_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: binomo2_backend
    restart: always
    ports:
      - "8081:8081"   # другой порт хоста для backend
    depends_on:
      - postgres

volumes:
  postgres2_data:
